/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Botones;

import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author LuisF
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/gas.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSalir = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        TituloPetrolin = new javax.swing.JLabel();
        Espaciofechayhora = new javax.swing.JTextField();
        Espaciocliente = new javax.swing.JTextField();
        FechaHora = new javax.swing.JLabel();
        ClienteName = new javax.swing.JLabel();
        Espaciotransaccion = new javax.swing.JTextField();
        Valtransaccion = new javax.swing.JLabel();
        buscartxt = new javax.swing.JTextField();
        Fondogas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalir.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(0, 0, 102));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        BotonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        BotonBuscar.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        BotonBuscar.setForeground(new java.awt.Color(0, 0, 102));
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        BotonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        BotonGuardar.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(0, 0, 102));
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        TituloPetrolin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/petrl.png"))); // NOI18N
        getContentPane().add(TituloPetrolin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Espaciofechayhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaciofechayhoraActionPerformed(evt);
            }
        });
        getContentPane().add(Espaciofechayhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 310, -1));

        Espaciocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioclienteActionPerformed(evt);
            }
        });
        getContentPane().add(Espaciocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 310, -1));

        FechaHora.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        FechaHora.setForeground(new java.awt.Color(255, 255, 255));
        FechaHora.setText("Fecha y hora efectiva:");
        getContentPane().add(FechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 170, -1));

        ClienteName.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        ClienteName.setForeground(new java.awt.Color(255, 255, 255));
        ClienteName.setText("Nombre del cliente:");
        getContentPane().add(ClienteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        Espaciotransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaciotransaccionActionPerformed(evt);
            }
        });
        getContentPane().add(Espaciotransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 310, -1));

        Valtransaccion.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Valtransaccion.setForeground(new java.awt.Color(255, 255, 255));
        Valtransaccion.setText("Valor de la transacción:");
        getContentPane().add(Valtransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 180, -1));
        getContentPane().add(buscartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 400, -1));

        Fondogas.setBackground(new java.awt.Color(255, 255, 255));
        Fondogas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inter.png"))); // NOI18N
        getContentPane().add(Fondogas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void EspaciofechayhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaciofechayhoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspaciofechayhoraActionPerformed

    private void EspacioclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioclienteActionPerformed

    private void EspaciotransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaciotransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspaciotransaccionActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        String a = Espaciocliente.getText();
        String b = Espaciotransaccion.getText();
        String c = Espaciofechayhora.getText();
        int  d = Integer.parseInt(b);
        Botones.guardar(a, d, c);
        
        Espaciocliente.setText("");
        Espaciotransaccion.setText("");
        Espaciofechayhora.setText("");
        
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        String buscar = buscartxt.getText();
        Botones.buscar(buscar);
        
        buscartxt.setText("");
    }//GEN-LAST:event_BotonBuscarActionPerformed
    public void cargardatos(Persona per){
        this.Espaciocliente.setText(per.getNombre());
        this.Espaciotransaccion.setText(Integer.toString(per.getTransaccion()));
        this.Espaciofechayhora.setText(per.getFecha());
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel ClienteName;
    private javax.swing.JTextField Espaciocliente;
    private javax.swing.JTextField Espaciofechayhora;
    private javax.swing.JTextField Espaciotransaccion;
    private javax.swing.JLabel FechaHora;
    private javax.swing.JLabel Fondogas;
    private javax.swing.JLabel TituloPetrolin;
    private javax.swing.JLabel Valtransaccion;
    private javax.swing.JTextField buscartxt;
    // End of variables declaration//GEN-END:variables
}
